config/routes.rb
Rails.application.routes.draw do
  default_url_options protocol: :https

  get '/mentors/new', to: "mentors#new"
  get '/students/new', to: "students#new"
  post '/signup', to: "registrations#create", as: 'new_user'

  get 'login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get'/logout', to: "sessions#destroy"

  get '/about', to: "welcome#about"

  get '/student/profile', to: "students#show", as: 'student'

  get '/mentor/profile', to: "mentors#show", as: 'mentor'
  post '/expertise', to: "expertises#create", as: 'expertise'


  resources :questions, except: [:index, :new, :edit, :destroy] do
    resources :ratings, only: [:new, :create]
  end

  root 'welcome#index'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :mentor, class_name: "User", optional: true
	belongs_to :student, class_name: "User"
	has_one :rating
	belongs_to :skill

  before_save :generate_url

  def generate_url
    poss = ('a'..'z').to_a+('A'..'Z').to_a+('0'..'9').to_a
    url = []
    5.times { url << poss.sample }
    self.codeshare_url = 'https://codeshare.io/' + url.join('')
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # before_action :is_user?, only: [:show]

  def show
    @user = current_user
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)
    @question.student_id = current_user.id
    if @question.save
      ActionCable.server.broadcast 'questions',
        content: @question.content,
        title: @question.title,
        skill: @question.skill.sub_type,
        tag: @question.tag,
        url: @question.id
        redirect_to "https://rubberduckapp.herokuapp.com/questions/#{@question.id}"
    end
  end

  def update
    @user = current_user
    @question = Question.find(params[:question_id])
    puts @question
    if @user.is_mentor
      @question.update(solved?: true, mentor_id: @user.id)
      redirect_to mentor_path
    else
      @question.update(solved?: true)
      redirect_to student_path
    end
  end


  private

  def is_user?
    question = Question.find(params[:id])
    student = User.find(question.student_id)
    current_user.id == question.mentor_id || current_user == student
  end

  def ssl_configured?
    !Rails.env.development?
  end

  def question_params
    params.require(:question).permit(:content, :title, :skill_id, :tag)
  end

end

app/views/questions/_question_form.html.erb
<h2> Ask a question: </h2>

<div class="container form-container">
  <%= form_for(question, url: questions_path) do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <div class="col-sm-10">
    <%= f.text_field :title, data: {textfield: "message"}%>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tag %>
    <div class="col-sm-10">
    <%= f.text_field :tag, data: {textfield: "message"}%>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :skill_id %>
    <div class="col-sm-10">
    <%= f.collection_select(:skill_id, Skill.all, :id, :sub_type)%>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <div class="col-sm-10">
    <%= f.text_area :content, data: {send: "message"}%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Ask"%>
    </div>
  </div>
  <% end %>
</div>

app/views/questions/show.html.erb
<header id="question-page">
  <div id="codeshare">
    <div id="codeshare-sidebar">
      <p>
        <% if @user.is_mentor %>
          <%= button_to "End Session", question_path(@question), method: :put, params: {question_id: @question.id} %>
        <% else %>
          <%= button_to "End Session", new_question_rating_path(@question), method: :get %>
        <% end %>
      </p>

      <label id="minutes">00</label>:<label id="seconds">00</label>
    </div>

    <iframe src="<%= @question.codeshare_url %>" height="100%" id="cs-iframe"></iframe>
    <script type='text/javascript'>
App.rooms = App.cable.subscriptions.create('RoomsChannel', {
  received: function(data) {
    return $('body').append(this.renderMessage(data));
  },
  renderMessage: function(data) {
    return "<div id='myOtherModal' class='modal show fade' tabindex='-1' role='dialog'><div id='moving-modal' class='modal-dialog'><div class='modal-content'><div class='modal-body'><h4>"+data.name+" has joined the room.</h4></div></div></div></div>"
  }
})
</script>
    <script type="text/javascript">
      var minutesLabel = document.getElementById("minutes");
      var secondsLabel = document.getElementById("seconds");
      var totalSeconds = 0;
      setInterval(setTime, 1000);

      function setTime()
      {
        ++totalSeconds;
        secondsLabel.innerHTML = pad(totalSeconds%60);
        minutesLabel.innerHTML = pad(parseInt(totalSeconds/60));
      }

      function pad(val)
      {
        var valString = val + "";
        if(valString.length < 2)
        {
          return "0" + valString;
        }
        else
        {
          return valString;
        }
      }
    </script>
  </div>
</header>