config/routes.rb
Rails.application.routes.draw do
  default_url_options protocol: :https

  get '/mentors/new', to: "mentors#new"
  get '/students/new', to: "students#new"
  post '/signup', to: "registrations#create", as: 'new_user'

  get 'login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get'/logout', to: "sessions#destroy"

  get '/about', to: "welcome#about"

  get '/student/profile', to: "students#show", as: 'student'

  get '/mentor/profile', to: "mentors#show", as: 'mentor'
  post '/expertise', to: "expertises#create", as: 'expertise'


  resources :questions, except: [:index, :new, :edit, :destroy] do
    resources :ratings, only: [:new, :create]
  end

  root 'welcome#index'

  mount ActionCable.server => '/cable'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
skip_before_action :authenticate_user!
  def index
  	if current_user
  		@user = current_user
  	end
  end

  def about
  end

end

app/views/welcome/about.html.erb
<header id="about-page">
  <div class="header-content">
    <div class="header-content-inner">
	    <h1>About Rubberduck</h1>
	    <br>
	    <h4>Our Mission</h4>
	    <p>Creating possibilities for students, teachers, and the industry as a whole to continue to grow</p>
	    <h4>About us</h4>
	    <p>Rubberduck.com is an online learning platform that helps anyone learn their favorite codebase to achieve personal and professional goals. Across borders, cultures, and languages, we’re proud to connect people who need coding help with people looking to earn money spreading their knowledge. We are committed to making the industry a stronger place, and our mentors aim to enrich the lives of aspiring developers as they grow and mature in their careers.</p>
    </div>
  </div>
</header> 

app/views/welcome/index.html.erb
<header>
  <div class="header-content">
    <div class="header-content-inner">
      <h1 id="main-tagline">Real problems, Real people<br>Real solutions</h1>
      <hr>
      <p id="main-subtag">We're creating stronger developers one problem at a time</p>
      <% if @user %>
        <%= link_to "Students", student_path, class: "btn btn-primary btn-xl page-scroll", id: "main-login" %>
        <%= link_to "Mentors", mentor_path, class: "btn btn-primary btn-xl page-scroll", id: "mentor-login" %>
      <% else %>
        <%= link_to "Students", login_path, class: "btn btn-primary btn-xl page-scroll", id: "main-button", html: {'data-toggle' => "modal", 'data-target' => "#myModal"} %>
        <%= link_to "Mentors", login_path, class: "btn btn-primary btn-xl page-scroll", id: "mentor-button", html: {'data-toggle' => "modal", 'data-target' => "#myModal"} %>
      <% end %>
    </div>
    <div class="header-content-inner">
      <%= link_to 'Register', students_new_path, class: "btn btn-primary btn-xl page-scroll", id: "register-button" %>
      <%= link_to 'Register', mentors_new_path, class: "btn btn-primary btn-xl page-scroll", id: "register-button" %>
    </div>
  </div>
</header>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header modal-header-success">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Login</h4>
      </div>
      <div class="modal-body">
        <%= render "sessions/form" %>
      </div>
    </div>

  </div>
</div>