config/routes.rb
Rails.application.routes.draw do
  default_url_options protocol: :https

  get '/mentors/new', to: "mentors#new"
  get '/students/new', to: "students#new"
  post '/signup', to: "registrations#create", as: 'new_user'

  get 'login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get'/logout', to: "sessions#destroy"

  get '/about', to: "welcome#about"

  get '/student/profile', to: "students#show", as: 'student'

  get '/mentor/profile', to: "mentors#show", as: 'mentor'
  post '/expertise', to: "expertises#create", as: 'expertise'


  resources :questions, except: [:index, :new, :edit, :destroy] do
    resources :ratings, only: [:new, :create]
  end

  root 'welcome#index'

  mount ActionCable.server => '/cable'
end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :question
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

	def new
		@rating = Rating.new
		@question = Question.find(params[:question_id])
	end

	def create
		@question = Question.find(params[:question_id])
		@rating = Rating.new(number: params[:rating][:number], question_id: params[:question_id])
		if @rating.save
			redirect_to student_path(current_user)
		else
			render :new
		end
	end

end

app/views/ratings/_rating_form.html.erb
<%= form_for(rating, url: question_ratings_path) do |f| %>
  <%= f.label :number, "1" %>
  <%= f.radio_button :number, '1', :checked => true %>
  <%= f.label :number, "2" %>
  <%= f.radio_button :number, '2' %>
  <%= f.label :number, "3" %>
  <%= f.radio_button :number, '3' %>
  <%= f.label :number, "4" %>
  <%= f.radio_button :number, '4' %>
  <%= f.label :number, "5" %>
  <%= f.radio_button :number, '5' %>

  <%= f.submit "Submit", id: "rating-submit" %>
<% end %>

app/views/ratings/new.html.erb
<header>
  <div id="main-rating">
    <div class="container-fluid">
      <% if @question.mentor_id != nil %>
      <h1>How was your session with <%= User.find(@question.mentor_id).username %>?</h1>
      <% else %>
      <h1>How was your session?</h1>
      <% end %>
      <h4 class="rating-subtag">Please rate your experience below</h4>

      <div class="row">
          <div class="col-sm-12">
            <%= render partial: "rating_form", locals: {rating: @rating} %>
          </div>
      </div>
      <h4>You can also tweet about it!</h4>
      <a href="https://twitter.com/intent/tweet?button_hashtag=Rubberduckapp&text=Another%20problem%20solved%20by" class="twitter-hashtag-button" data-size="large">Tweet #Rubberduckapp</a>
    </div>
  </div>
</header>