config/routes.rb
Rails.application.routes.draw do
  default_url_options protocol: :https

  get '/mentors/new', to: "mentors#new"
  get '/students/new', to: "students#new"
  post '/signup', to: "registrations#create", as: 'new_user'

  get 'login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get'/logout', to: "sessions#destroy"

  get '/about', to: "welcome#about"

  get '/student/profile', to: "students#show", as: 'student'

  get '/mentor/profile', to: "mentors#show", as: 'mentor'
  post '/expertise', to: "expertises#create", as: 'expertise'


  resources :questions, except: [:index, :new, :edit, :destroy] do
    resources :ratings, only: [:new, :create]
  end

  root 'welcome#index'

  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
   <title>Rubberduck</title>
   <%= csrf_meta_tags %>
   <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>

    <!-- FAVICON -->
    <link rel="shortcut icon" href="../assets/favicon.ico" type="image/x-icon">
    <link rel="icon" href="../assets/favicon.ico" type="image/x-icon">
    <!-- FONT AWESOME -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- FONTS -->
    <link href='//fonts.googleapis.com/css?family=Hammersmith+One' rel='stylesheet' type='text/css'>

    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>

  </head>

  <body>
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand page-scroll" href="/">Rubberduck</a>
              <a class="navbar-brand page-scroll" id="main-logo"></a>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <%= link_to "About", about_path, class: "page-scroll" %>
                </li>
                <li>
                  <% if logged_in? %>
                  <%= link_to "Logout", logout_path, action: 'destroy', class: "page-scroll" %>
                  <% end %>
                </li>
              </ul>
          </div>
      </div>
    </nav>

    <%= yield %>

    <footer class="text-center">
      <div id="footer-parent" class="footer-below">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              Copyright &copy; Rubberduck 2016 | Special Thanks: Codeshare.io
            </div>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>